[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.19.2"
quilt_mappings = "1.19.2+build.1"
fabric_loader = "0.14.9"

fabric_api = "0.59.0+1.19.2" # Don't forget to add +{$mc_version} to end of this
midnightlib = "0.5.2"
commandstructures = "3.0.0+1.19"
structurevoidtoggle = "4.0.0+1.19"
mod_menu = "4.0.6"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
# [bundles]
# example = ["example-a", "example-b", "example-c"]

[plugins]
fabric_loom = { id = "fabric-loom", version = "0.12.+" }
